### ISSUE TITLE
S3 classes for internal objects

### ISSUE THREAD

**Issue by wlandau** [ropensci/drake#1115]
## Prework

- [x] Read and abide by `drake`'s [code of conduct](https://github.com/ropensci/drake/blob/master/CODE_OF_CONDUCT.md).
- [x] Search for duplicates among the [existing issues](https://github.com/ropensci/drake/issues), both open and closed.

## Description

Related: #1114. Objects that should be environments with S3 class attributes:b

- [ ] Target specs, re #1114.
- [ ] Code analysis results lists returned by `analyze_code()`.
- [ ] Objects returned by `trigger()`.
- [ ] The "command" object proposed in https://github.com/ropensci/drake/issues/1114#issuecomment-565871832.
- [ ] `config$control` as proposed in #965.

**Comment by wlandau** [comment]
On reflection, cleaned-up data structures should be enough. It takes extra compute time to assign classes. Not worth spending it for this.

**Comment by wlandau** [comment]
Maybe just `config$control`

**Comment by wlandau** [comment]
Revisited this. Implementing for `drake_config()` objects, etc. Not for environments.

**Comment by wlandau** [comment]
Added S3 classes and pretty print methods in b21fb90fda910ac64e41352e7231f4d9a15d33c6.
