### ISSUE TITLE
Dynamic files

### ISSUE THREAD

**Issue by wlandau** [ropensci/drake#1168]
## Prework

- [x] Read and abide by `drake`'s [code of conduct](https://github.com/ropensci/drake/blob/master/CODE_OF_CONDUCT.md).
- [x] Search for duplicates among the [existing issues](https://github.com/ropensci/drake/issues), both open and closed.

## Background

I would like to return where we left off in #1127. Not only could dynamic files work around the rigidity of `file_out()`, they they might also provide the best solution to #1112 (related:  https://twitter.com/MilesMcBain/status/1227082065385943040, cc @MilesMcBain).

**Comment by wlandau** [comment]
## Proposal

Try https://github.com/ropensci/drake/issues/1127#issuecomment-570286140 again, but with a cleaner separation between the code bases of static vs dynamic files.

## API

Let's go with the API proposed in https://github.com/ropensci/drake/issues/1127#issuecomment-570286140.

```r
drake_plan(
  paths = target(
    some_paths,
    format = "file"
  )
)
```

## Scope

This new format should cover local files and directories only. URLs have special concerns because time delays are more of an issue, so we can think about `format = "url"` later on.

## Triggers

- [ ] Dynamic files will incur an extra trigger, which requires a new argument to `trigger()`, e.g. `trigger(dynamic_file = TRUE)`. Should be simple enough to implement this interface piece since it will not have the baggage of `condition` or `change` triggers.
- [ ] Unlike the other triggers, this one is sub-target-specific. So we need some refactoring to allow some triggers to apply to sub-targets. The initial wave of dynamic branching assumed all triggers were static, so this will be difficult, and there will be a lot of technical debt to overcome.

## Recovery

- [ ] If a dynamic sub-target's dynamic file is broken, we do not want to recover it in `make(recover = TRUE)`. So we have to adjust the recovery keys of dynamic sub-targets to account for this.

## HPC checksums

- [ ] In HPC, `drake` waits for static files to arrive over the network file system before it moves on to other targets. The mechanism works by computing checksums. We need these checksums to account for dynamic files.

**Comment by wlandau** [comment]
> Unlike the other triggers, this one is sub-target-specific. So we need some refactoring to allow some triggers to apply to sub-targets. 

We can handle this in `register_subtargets()` and `finalize_meta()`.

**Comment by wlandau** [comment]
> The initial wave of dynamic branching assumed all triggers were static, so this will be difficult, and there will be a lot of technical debt to overcome.

Well, maybe not. Now that `handle_triggers()` is full of S3 dispatch, it does not seem so bad.

I do see a lot of technical debt looking over old code, but a lot of it is static branching technical debt, which is forgivable.

**Comment by wlandau-lilly** [comment]
Another thing I remembered: the target value (character vector of paths) needs to have a single hash (as an attribute) to invalidate downstream targets when appropriate. Individual file/directory hashes, along with their time stamps and sizes, should go in the metadata.

**Comment by wlandau** [comment]
But that means creating a new data type, which means we need to worry about how slicing and concatenation work...

**Comment by wlandau** [comment]
For `format = "file"` and similar targets, we could consider [record-style objects](https://vctrs.r-lib.org/articles/s3-vector.html#record-style-objects) with [`new_rcrd()`](https://vctrs.r-lib.org/reference/new_rcrd.html).

**Comment by wlandau** [comment]
## New proposal for dynamic files

1. A new "reference"` format for any kind of dynamic external data.
2. New function `ref_file()` to create a [record-style object](https://vctrs.r-lib.org/articles/s3-vector.html#record-style-objects) pointing to a file.
3. Internal checks that (1) and (2) are either used together or not at all.

```r
drake_plan(
  paths = target(
    ref_file(some_file_paths),
    format = "reference"
  )
)
```

## Advantages

1. Predictable, well-behaved return types.
2. Easier extensibility to other kinds of dynamic data, e.g. cloud (#1112).

**Comment by wlandau** [comment]
Note: like earlier proposals, https://github.com/ropensci/drake/issues/1168#issuecomment-588227576 is fully dynamic. `ref_file()` will not require literal file path arguments. However, the return value of the target does somehow need to be a `ref_file()` object.

**Comment by wlandau** [comment]
- [ ] `ref_file()` objects should behave like character vectors. `writeLines("lines", x)` should automatically write those lines to `vctrs::field(x, "path")`. Let's see if we can accomplish this with S3 methods for coercion and casting as [described here](https://vctrs.r-lib.org/articles/s3-vector.html#record-style-objects).

**Comment by wlandau** [comment]
Disadvantages of record-style objects:

1. The user needs to cast them with `as.character()` before character-like operations.
2. Every field must be a vector, which might not necessarily be the case in #1112.

**Comment by wlandau** [comment]
You know what? We don't actually need https://github.com/ropensci/drake/issues/1168#issuecomment-588227576. We can cleverly store the file paths with their hashes (so things are hashed properly) and just return the paths to the user using decorated `storr` methods. This is something I had not thought to do until now, and specialized formats actually are a good fit for the implementation.

First, we give the value its own hash.

https://github.com/ropensci/drake/blob/aa5170784c5af1504fe26487064ca2fbf2e9d991/R/store_outputs.R#L8

https://github.com/ropensci/drake/blob/aa5170784c5af1504fe26487064ca2fbf2e9d991/R/store_outputs.R#L22-L33

We store it in the metadata, along with other information that helps us check if the target is up to date.

https://github.com/ropensci/drake/blob/aa5170784c5af1504fe26487064ca2fbf2e9d991/R/store_outputs.R#L208

https://github.com/ropensci/drake/blob/aa5170784c5af1504fe26487064ca2fbf2e9d991/R/store_outputs.R#L216-L232

When it comes time to store the value, we store it with its hash.

https://github.com/ropensci/drake/blob/aa5170784c5af1504fe26487064ca2fbf2e9d991/R/decorate_storr.R#L401-L403

But when we retrieve the value for the user, we drop the hash and just get the path (a character vector).

https://github.com/ropensci/drake/blob/aa5170784c5af1504fe26487064ca2fbf2e9d991/R/decorate_storr.R#L330-L332

https://github.com/ropensci/drake/blob/aa5170784c5af1504fe26487064ca2fbf2e9d991/R/decorate_storr.R#L393-L395

**Comment by wlandau** [comment]
As of https://github.com/ropensci/drake/commit/aa5170784c5af1504fe26487064ca2fbf2e9d991, we can store and retrieve the file hashes and metadata, and we give character vectors to the user just as expected. so far so good.

## Roadmap

- [ ] Write a function to check if a dynamic file is up to date. Use an S3 framework to establish placeholders for other similar formats.
- [ ] Use it to check static targets in `handle_triggers()`.
- [ ] Use it to check dynamic sub-targets in `filter_subtargets()`.
- [ ] Use it in `is_outdated()`.
- [ ] Recovery keys.
- [ ] HPC checksums.

## Tests

- [ ] Test just the function at the top level of the roadmap.
    - [ ] Compute correct hash.
    - [ ] Use old hash if the time stamp and file size are appropriate.
- [ ] Recovery key includes file path and hash.
- [ ] HPC checksum includes dynamic file hashes.
- [ ] Replicate HPC checksum tests.
- [ ] In a `drake` workflow.
    - [ ] Change a file's content and observe downstream invalidation.
    - [ ] Change a file's time stamp and observe targets are still valid.
    - [ ]  Rebuild a dynamic file with the same hash and observe downstream targets still valid.
    - [ ] `clean()` and recover the latest target.
    - [ ] Revert the file and recover an old target. Check that it is up to date afterwards.
    - [ ] Change the file to a totally new value and observe no data recovery.
- [ ] Repeat the above tests.
    - [ ] Do for static targets.
    - [ ] Repeat for dynamic branching.
    - [ ] Repeat for directories.

**Comment by wlandau** [comment]
Just realized data recovery will not always be possible because historical dynamic files are buried in old metadata we may not be able to find.

**Comment by wlandau** [comment]
Implemented via #1178.
