### ISSUE TITLE
A quicker end to staged parallelism

### ISSUE THREAD

**Issue by wlandau** [ropensci/drake#369]
## The problem

With the exception of `make(parallelism = "future")` and `make(parallelism = "Makefile")`, `drake` has an embarrassing approach to parallelism, both literally and figuratively. It divides the dependency graph into conditionally independent stages and then runs those stages sequentially. Targets only run in parallel within those stages. In other words, `drake` waits for the slowest target to finish before moving to the next stage.

![capture](https://user-images.githubusercontent.com/1580860/39472822-a6d211b6-4d19-11e8-820c-1e4c05f637cf.PNG)

At the time, I could not find an R package to traverse an arbitrary network of jobs in parallel. (**Stop me right here if such a tool actually exists!**) Parallel computing tools like `foreach`, `parLapply`, `mclapply`, and `future_lapply` all assume the workers can act independently. So I thought staged parallelism was natural. However, I was thinking within the constraints of the available technology, and parallel efficiency suffered.

## Long-term work

In late February, I started the [`workers`](https://github.com/wlandau/workers) package. If you give it a job network and a parallel computing technology, the goal is to traverse the graph using a state-of-the-art algorithm. It has a proof-of-concept implementation and an initial [design specification](https://github.com/wlandau/workers/tree/master/specification), but it has a long way to go. At this stage, it really needs an R-focused [message queue](http://queues.io/). I was hoping [`liteq`](https://github.com/r-lib/liteq) would work, but due to an [apparent race condition](https://github.com/r-lib/liteq/issues/17) and some speed/overhead issues on my end, I am stuck for the time being.

## Now

I say we rework the `make(parallelism = "mclapply")` and `make(parallelism = "parLapply")` backends natively. As I see it, `make(parallelism = "mclapply", jobs = 2)` should fork 3 processes: 2 workers and 1 master. The master sends jobs to the workers in the correct order at the correct time, and the workers keep coming back for more without stopping. The goal is to minimize idleness and overhead.

The implementation will be similar to `make(parallelism = "future", caching = "worker")` (see [`future.R`](https://github.com/ropensci/drake/blob/master/R/future.R)). I think the implementation should go into `drake` itself because 

1. The code should be relatively short, and
2. I do not want to lock in the design of [`workers`](https://github.com/wlandau/workers) until I get the chance to do an extensive lit review of parallel graph algorithms.

## To-do's:

- [x] (Re)implement the low-overhead parallel backends.
    - [x] `run_lapply()` (Just loop through a toposort of the targets.)
    - [x] `run_mclapply()`
    - [x] `run_parLapply()`
    - [x] `run_future_lapply()` (We still might want persistent workers on a cluster.)
- [x] Use `on.exit(set_done(...))` to handle failures on both the master process and the workers.
- [x] Skip on CRAN any unit tests that spawn more than 2 processes.
- [x] For all non-distributed parallel backends, do not wait for all the imports before starting the targets.
- [x] Visualize graphs as regular DAGs without any parallel staging.
- [x] Retire functions `parallel_stages()`, `max_useful_jobs()`, and `rate_limiting_times()`.
- [x] Re-implement `predict_runtime()`.
- [ ] Rewrite the [parallel computing vignette](https://ropensci.github.io/drake/articles/parallelism.html) and the [timing vignette](https://ropensci.github.io/drake/articles/timing.html)
- [ ] Remove mentions of staged parallelism from the rest of the documentation.

**Comment by wlandau** [comment]
I have begun work on this in the [`i369-mclapply` branch](https://github.com/ropensci/drake/tree/i369-mclapply). It has loads of errors and I am super short on time these days, but I am optimistic because this is a problem I think I already know how to solve.

**Comment by wlandau** [comment]
The next step now is to make the `"future_lapply"` backend use persistent workers rather than staged parallelism. Why am I bothering with this when we already have `make(parallelism = "future")`? Because the `"future"` backend (without the `"lapply"` part) supports transient workers, not persistent workers. That's one worker per job. It's the right call for clusters with strict wall time limits, but it's a lot of overhead, especially if those jobs get sent to a cluster. I want `make(parallelism = "future_lapply", jobs = 4)`, on the other hand, to launch 4 cluster workers that build any number of targets within the time constraints.

Two things I learned so far in the [`i369-future_lapply` branch](https://github.com/ropensci/drake/tree/i369-future_lapply):

1. Workers in `future_lapply()` are not always concurrent, particularly with `future::plan(sequential)`. So we need a special `callr::r_bg()` process to act as master.
2. My first dig a non-staged `make(parallelism = "future_lapply")` hangs/stalls, and I do not know why just yet. And tomorrow I need to deal with a surprise at work, so I am unlikely to finish it by the end of the week.

**Comment by wlandau** [comment]
A very important piece I forgot: `on.exit({traceback(); set_all_workers_done()})`. Otherwise, one failure on master will keep them hanging in `while()` loops. In general, I need a robust way to detect crashed workers.

On `liteq`, this is accomplished with connections. With multiple sessions running `drake` workers, I might instead have `on.exit({traceback(); set_done()})` to make sure the master process doesn't worry about it any more.

I should implement this before I debug the `future_lapply` backend. If it works, `make(parallelism = "future_lapply")` will stop hanging.

**Comment by krlmlr** [comment]
I'm now seeing some overhead for targets that are cheap to compute but require large-ish input data:

```r
library(tidyverse)
library(drake)

N <- 500

gen_data <- function() {
  tibble(a = seq_len(N), b = 1, c = 2, d = 3)
}

plan_data <- drake_plan(
  data = gen_data()
)

plan_sub <-
  gen_data() %>%
  transmute(
    target = paste0("data", a),
    command = paste0("data[", a, ", ]")
  )

plan <- 
  bind_rows(plan_data, plan_sub)

system.time(drake::make(plan, jobs = 8))
```

CRAN version with `mclapply()`: 17 seconds user time, 4 seconds elapsed

GitHub revision 08c67c8: 68 seconds user time, 30 seconds elapsed

Is this intended?

**Comment by wlandau** [comment]
Your reprex is a perfect demonstration of what we're potentially sacrificing in #369. And yes, I did expect to have more overhead, especially at first. Staged parallelism excels when we have a large number of conditionally independent targets (i.e. tall dependency graphs).

![screenshot_20180505_140555](https://user-images.githubusercontent.com/1580860/39666196-a99b17c4-506d-11e8-86ff-1a576c9457c3.png)

In the CRAN version of `drake`, you're essentially just using `mclapply()` to get all the rows of the data, and all the workers are autonomous. No bottleneck for embarrassingly/perfectly parallel tasks. But in the development version, the master process has check all the workers and assign them targets one by one. My guess is that our biggest loss in efficiency happens when the master loops over all the workers one by one to check if each one is idle.

https://github.com/ropensci/drake/blob/7fe45f097ba8a33a7020f9723034692a938b418c/R/mclapply.R#L55-L75

If there is a way for the master to jump straight to the idle workers, I suspect/hope the master will be faster.

Part of the trouble is that I am using [`storr`](https://github.com/richfitz/storr) to communicate with the workers. While [`storr`](https://github.com/richfitz/storr)'s RDS cache is reasonably thread safe, it's not actually a designed for this purpose. As you alluded to before, what we really need in the long term is a solid, fast, scalable, thread safe message queue. I tried [`liteq`](https://github.com/r-lib/liteq) for [`workers`](https://github.com/wlandau/workers), but the locking mechanism has [a lot of overhead of its own](https://github.com/r-lib/liteq/blob/23ca7f8cd69f1816a88de5602a3ae358c913ecb8/R/db.R#L314) and [is not totally thread safe for all variants of SQL](https://github.com/r-lib/liteq/issues/17).

**Comment by krlmlr** [comment]
In the code chunk above I don't understand what happens if `length(target)` is zero.

We're seeing a lot of user time spent for the GitHub version, this can't be just because the master is busy. Are the workers using busy waiting?

Profiling the master loop shows that most of the time is spent in `mc_is_idle()`: http://rpubs.com/krlmlr/drake-369-profile.

Can you implement an efficient "enumerate all idle workers" with *storr*? Perhaps if you had a *storr* namespace for each state and each worker would register/unregister itself from that namespace when the state changes?

**Comment by wlandau** [comment]
For anyone else looking on, I have added back staged parallelism in some additional backends: `make(parallelism = "mclapply_staged")` and `make(parallelism = "parLapply_staged")`. The `make(parallelism = "mclapply")` and `make(parallelism = "parLapply")` still use sensible persistent workers and have nothing to do with staged parallelism.

All the code for staged parallelism is in `R/staged.R`, and if we ever decide to remove staged parallelism completely, all we need to do is remove the file. The difference that #369 makes is that staged parallelism is just an afterthought and not entangled in the core internals.

**Comment by wlandau** [comment]
Update: we have a new [timing vignette](https://ropensci.github.io/drake/articles/timing.html). See the [strategy section](https://ropensci.github.io/drake/articles/timing.html#strategize-your-high-performance-computing) to see how `predict_runtime()` and `predict_load_balancing()` can help you plan the scale of your workflow. I am super excited about this! `Drake` is starting to mature as a serious parallel computing engine!

**Comment by wlandau** [comment]
We now have a new and improved [parallelism guide](https://ropensci.github.io/drake/articles/parallelism.html). Much clearer and up to date.

This issue was quite the exciting sprint. I am really looking forward to testing and iterating on the newly reworked backends. Please help spread the word.

**Comment by wlandau** [comment]
To recap: `drake` has 3 parallel scheduling now, as demonstrated by the [videos embedded here](https://ropensci.github.io/drake/articles/parallelism.html#scheduling-algorithms). @krlmlr and @gaborcsardi, I have been thinking for the last 3 months about our vigorous conversation about `revdepcheck` at `RStudio::conf(2018)`, and I am happy to say that `drake` is much better able to perform this kind of work efficiently.

**Comment by wlandau** [comment]
FYI: @krlmlr, coordination among persistent workers seems to be much faster now after the work I did this weekend. Scheduling is now based on `drake`'s own [`liteq`-like message queue](https://github.com/ropensci/drake/blob/master/R/message_queue.R), which I will soon release as a separate package.

**Comment by wlandau** [comment]
Things just got even faster in fea4acb74efe00f63656fadb77cf4780af7e89f5. We'll let it play out, but there is a good chance we'll find we won't need staged parallelism anymore.

**Comment by wlandau** [comment]
`"mclapply_staged"` also appears faster than the `clustermq`-based backends.

``` r
system.time(drake::make(plan, parallelism = "mclapply_staged", jobs = 8))
#> target data
#>    user  system elapsed 
#>   2.638   0.133   4.490
```

``` r
options(clustermq.scheduler = "multicore")
system.time(drake::make(plan, parallelism = "clustermq", jobs = 8, verbose = FALSE))
#> Submitting 8 worker jobs (ID: 6150) ...
#> Master: [11.3s 97.5% CPU]; Worker: [avg 1.8% CPU, max 311.3 Mb]
#>    user  system elapsed 
#>  13.854   0.523  14.698
```

``` r
options(clustermq.scheduler = "multicore")
system.time(drake::make(plan, parallelism = "clustermq_staged", jobs = 8, verbose = FALSE))
#> Submitting 8 worker jobs (ID: 6752) ...
#> Running 1 calculations (1 calls/chunk) ...
#> Running 500 calculations (1 calls/chunk) ...
#> Master: [4.7s 86.1% CPU]; Worker: [avg 4.7% CPU, max 310.8 Mb]
#>    user  system elapsed 
#>   6.465   0.299   7.415
```

On the other hand, I am not sure how much `drake` should accommodate projects that spread work so thinly over so many targets. Maybe packing and unpacking could compensate (#304).
